### ISSUE TITLE
Cookie, bypass browser and password check

### ISSUE THREAD

**Issue by HenryQuan** [HenryQuan/AnimeOne#5]
# Why?
Sometimes, the website will check if the request is from a legit browser and block my app's request. This has been the case so far but by getting `cookie` from webview, this can be bypassed. The app will simply popup a new page displaying the website and as soon as, it passes the check. It will call some native codes to get the cookie because it is `httponly` and you cannot use JS to retrieve it. It might be a good time to try using native codes. This is really important in the future and maybe it is time to try it now.

# TODO
- [x] Native code for Android
   - [x] Get cookie from native webview
- [x] Call it from Flutter side
- [X] Save it locally and repeat when needed
- [x] Add a loading indicator above the webview, disable touch input and disable back button
- [X] Save cookie to shared preference since flutter uses the same interface

However, this doesn't work. With the correct user agent, I can sometime load on my emulator. I have passed user agent back to native. I might create a model to hold data from native.

# Extra
~~*This has a low priority now*~~ because you can just use the browser instead but it might be good at some points to solve this issue. This can also be converted into my first flutter module.
